#!/bin/bash
#
# ccpa - C to Analytical Engine Compiler
# Copyright (C) 2017 Christopher Chianelli
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
SCRIPT_DIR=-PATH-
outfile=punchcards
cmd="a"
optimize="y"

output_file ()
{
    if [[ $outfile ]]
    then
        mv $SCRIPT_DIR/temp/out "$outfile"
    else
        cat $SCRIPT_DIR/temp/out
    fi
}

echoerr() { echo "$@" 1>&2; }

while getopts ":p:s:t:o:n:q" o; do
    case "${o}" in
        p)
            cmd="p"
            ;;

        s)
            cmd="s"
            ;;

        t)
            cmd="t"
            ;;

        o)
            outfile=$OPTARG
            ;;

        n)
            outfile=""
            ;;

        q)
            optimize="n"
            ;;

        *)
            echo "Invalid option"
            exit 1
            ;;
    esac
done
file="${@: -1}"
gcc -E $file | $SCRIPT_DIR/scanner/cparse  > $SCRIPT_DIR/temp/out
if [[ $? -eq 0 ]]
then
    if [[ "$cmd" == "s" ]]
    then
        output_file
    else
        ($SCRIPT_DIR/scanner/treegen < $SCRIPT_DIR/temp/out) > $SCRIPT_DIR/temp/out1
        success=$?
        mv $SCRIPT_DIR/temp/out1 $SCRIPT_DIR/temp/out
        if [[ $success -eq 0 ]]
        then
            if [[ "$cmd" == "t" ]]
            then
                output_file
            else
                (java -cp $SCRIPT_DIR/optimization/bin run/TreeOptimizer < $SCRIPT_DIR/temp/out) > $SCRIPT_DIR/temp/out1
                success=$?
                mv $SCRIPT_DIR/temp/out1 $SCRIPT_DIR/temp/out
                if [[ $success -eq 0 ]]
                then
                    if [[ "$cmd" == "p" ]]
                    then
                        output_file
                    else
                        ( java -cp $SCRIPT_DIR/backend/treeToAE2/bin run/TreeToAE2 $optimize < $SCRIPT_DIR/temp/out) > $SCRIPT_DIR/temp/out1
                        success=$?
                        mv $SCRIPT_DIR/temp/out1 $SCRIPT_DIR/temp/out
                        if [[ $success -eq 0 ]]
                        then
                            (bash $SCRIPT_DIR/backend/mk_src/compile_ae2.bash < $SCRIPT_DIR/temp/out) > $SCRIPT_DIR/temp/out1
                            success=$?
                            mv $SCRIPT_DIR/temp/out1 $SCRIPT_DIR/temp/out
                            if [[ $success -eq 0 ]]
                            then
                                output_file
                            else
                                echoerr "Compilation Failed"
                            fi
                        else
                            echoerr "Compilation Failed"
                        fi
                    fi
                else
                    echoerr "Compilation Failed"
                fi
            fi
        else
            echoerr "Compilation Failed"
        fi
    fi
else
    echoerr "Compilation Failed"
fi
