#!/bin/bash
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
outfile=punchcards
cmd="a"

while getopts ":p:s:t:o:n" o; do
    case "${o}" in
        p)
            cmd="p"
            ;;

        s)
            cmd="s"
            ;;

        t)
            cmd="t"
            ;;

        o)
            outfile=$OPTARG
            ;;

        n)  
            outfile=""
            ;;

        *)
            echo "Invalid option"
            exit 1
            ;;
    esac
done
file="${@: -1}"
case "$cmd" in
    p)
        command="gcc -E $file | $SCRIPT_DIR/scanner/cparse | $SCRIPT_DIR/scanner/treegen | java -cp $SCRIPT_DIR/optimization/bin run/TreeOptimizer | xmllint --format -"
        ;;
    s)
        command="gcc -E $file | $SCRIPT_DIR/scanner/cparse"
        ;;

    t)
        command="gcc -E $file | $SCRIPT_DIR/scanner/cparse | $SCRIPT_DIR/scanner/treegen | xmllint --format -"
        ;;

    *)
        command="gcc -E $file | $SCRIPT_DIR/scanner/cparse | $SCRIPT_DIR/scanner/treegen | java -cp $SCRIPT_DIR/optimization/bin run/TreeOptimizer | java -cp $SCRIPT_DIR/backend/treeToAE2/bin run/TreeToAE2 | bash $SCRIPT_DIR/backend/mk_src/compile_ae2.bash"
        ;;
esac

if [[ $outfile ]]
then
eval $command > $outfile
else
eval $command
fi
