#!/bin/bash
cd scanner
make clean
make
cd ..

rm tests/out/*
rm tests/opt-out/*

for i in `ls tests`
do
if [ -f "tests/$i" ]
then
    ./ccpa -q -o "tests/out/`echo $i | sed 's/\(.*\)\..*/\1/'`.ae" "tests/$i"
    ./ccpa -o "tests/opt-out/`echo $i | sed 's/\(.*\)\..*/\1/'`.ae" "tests/$i"
fi
done
