#!/bin/bash
cd scanner
make clean
make
cd ..

for i in `ls tests`
do
if [ -f "tests/$i" ]
then
    ./ccpa -o "tests/out/`echo $i | sed 's/\(.*\)\..*/\1/'`.ae" "tests/$i" #2>&1 >/dev/null | xmllint --format -
fi
done
